FROM centos:7

RUN yum install -y -q \
        centos-release-scl \
        epel-release && \
    yum install -y -q  \
        rh-python36 && \
    /opt/rh/rh-python36/root/usr/bin/python3.6 -m venv venv

# Default pip is too old for manylinux wheels
RUN venv/bin/pip install -U pip

ADD test.sh zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl /
RUN /test.sh
